"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import { supabase } from "@/lib/supabase/client"
import {
  Loader2,
  Send,
  ExternalLink,
  Search,
  Sparkles,
  HelpCircle,
  TrendingUp,
  Brain,
  Copy,
  Check,
  Plus,
  BookOpen,
  Wand2,
} from "lucide-react"
import { toast } from "@/hooks/use-toast"

interface PAAQuestion {
  question: string
  search_intent: string
  geo_strategy?: string
}

interface RedditSource {
  subreddit: string
  title: string
  url: string
}

interface QuestionsResult {
  business: string
  cached: boolean
  status: string
  threads_analyzed: number
  subreddits: string[]
  sources: RedditSource[]
  questions: PAAQuestion[]
  bonus_topics: string[]
}

function parseInline(text: string): string {
  // Bold: **text**
  let parsed = text.replace(/\*\*(.*?)\*\*/g, '<strong class="font-extrabold text-foreground tracking-tight select-text font-sans">$1</strong>')
  
  // Italic: *text* (avoiding double stars)
  parsed = parsed.replace(/\*(.*?)\*/g, '<em class="italic text-foreground/90 select-text font-sans">$1</em>')
  
  // Inline Code: `code`
  parsed = parsed.replace(/`(.*?)`/g, '<code class="px-1.5 py-0.5 rounded bg-secondary/80 text-[11px] font-mono text-accent select-all">$1</code>')
  
  return parsed
}

function parseMarkdownToHtml(markdown: string): string {
  if (!markdown) return ""
  
  // Pre-process: standardize newlines
  const normalized = markdown.replace(/\r\n/g, "\n")
  
  // Split into blocks by double newlines or sequential newlines
  const blocks = normalized.split(/\n\n+/)
  
  const parsedBlocks = blocks.map(block => {
    const trimmed = block.trim()
    if (!trimmed) return ""
    
    // Check if it's a heading
    if (trimmed.startsWith("### ")) {
      const text = trimmed.substring(4)
      return `<h3 class="text-sm font-semibold tracking-tight text-foreground mt-6 mb-3 flex items-center gap-2 border-l-2 border-accent pl-2.5 select-text font-sans">${parseInline(text)}</h3>`
    }
    if (trimmed.startsWith("## ")) {
      const text = trimmed.substring(3)
      return `<h2 class="text-base font-bold tracking-tight text-foreground mt-7 mb-4 flex items-center gap-2 border-b border-border/10 pb-2 select-text font-sans">${parseInline(text)}</h2>`
    }
    if (trimmed.startsWith("# ")) {
      const text = trimmed.substring(2)
      return `<h1 class="text-lg font-black tracking-tight text-foreground mt-8 mb-5 border-b-2 border-accent/20 pb-2.5 select-text font-sans">${parseInline(text)}</h1>`
    }
    
    // Check if it's an HTML table or contains HTML table tags
    if (trimmed.includes("<table") || trimmed.includes("<tbody") || trimmed.startsWith("<table>")) {
      // Clean and normalize HTML tags to strip all custom styles/classes/attributes generated by LLM
      let styledTable = trimmed
        .replace(/<table[^>]*>/gi, "<table>")
        .replace(/<thead[^>]*>/gi, "<thead>")
        .replace(/<tbody[^>]*>/gi, "<tbody>")
        .replace(/<tr[^>]*>/gi, "<tr>")
        .replace(/<th[^>]*>/gi, "<th>")
        .replace(/<td[^>]*>/gi, "<td>")
      
      // If it doesn't have a <table> wrap, let's add it
      if (!styledTable.includes("<table>") && styledTable.includes("<tbody>")) {
        styledTable = `<table>${styledTable}</table>`
      }
      
      // Inject standard, theme-aware widescreen comparative table classes
      styledTable = styledTable.replace(/<table>/gi, '<div class="overflow-x-auto my-5 rounded-xl border border-border/30 bg-secondary/5 shadow-sm"><table class="w-full text-left border-collapse select-text font-sans">')
      styledTable = styledTable.replace(/<\/table>/gi, '</table></div>')
      styledTable = styledTable.replace(/<thead>/gi, '<thead class="bg-secondary/40 border-b border-border/20 select-none">')
      styledTable = styledTable.replace(/<tr>/gi, '<tr class="border-b border-border/10 last:border-b-0 hover:bg-accent/[0.02] transition-colors">')
      styledTable = styledTable.replace(/<th>/gi, '<th class="px-4 py-3 text-xs font-bold uppercase tracking-wider text-foreground select-none">')
      styledTable = styledTable.replace(/<td>/gi, '<td class="px-4 py-3.5 text-[12px] text-muted-foreground/90 font-medium leading-relaxed align-top">')
      
      // Normalize any inline tags inside the table cells
      styledTable = styledTable.replace(/<strong>(.*?)<\/strong>/gi, '<strong class="font-extrabold text-foreground select-text">$1</strong>')
      styledTable = styledTable.replace(/\*\*(.*?)\*\*/g, '<strong class="font-extrabold text-foreground select-text">$1</strong>')
      styledTable = styledTable.replace(/\*(.*?)\*/g, '<em class="italic text-foreground/90 select-text">$1</em>')
      return styledTable
    }
    
    // Check if it's a Markdown table
    if (trimmed.startsWith("|")) {
      const lines = trimmed.split("\n")
      let tableHtml = `<div class="overflow-x-auto my-5 rounded-xl border border-border/30 bg-secondary/5 shadow-sm"><table class="w-full text-left border-collapse select-text font-sans">`
      let headers: string[] = []
      let rows: string[][] = []
      
      lines.forEach((line, idx) => {
        const cells = line.split("|").map(c => c.trim()).filter((_, i, arr) => i > 0 && i < arr.length - 1)
        if (idx === 0) {
          headers = cells
        } else if (idx === 1) {
          // Alignment row, skip
        } else {
          rows.push(cells)
        }
      })
      
      if (headers.length > 0) {
        tableHtml += `<thead class="bg-secondary/40 border-b border-border/20 select-none"><tr>`
        headers.forEach(h => {
          tableHtml += `<th class="px-4 py-3 text-xs font-bold uppercase tracking-wider text-foreground select-none">${parseInline(h)}</th>`
        })
        tableHtml += `</tr></thead>`
      }
      
      tableHtml += `<tbody>`
      rows.forEach(row => {
        tableHtml += `<tr class="border-b border-border/10 last:border-b-0 hover:bg-accent/[0.02] transition-colors">`
        row.forEach(td => {
          tableHtml += `<td class="px-4 py-3.5 text-[12px] text-muted-foreground/90 font-medium leading-relaxed align-top">${parseInline(td)}</td>`
        })
        tableHtml += `</tr>`
      })
      tableHtml += `</tbody></table></div>`
      return tableHtml
    }
    
    // Check if it's a list
    if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
      const items = trimmed.split(/\n[-*]\s+/).map(item => {
        let clean = item
        if (clean.startsWith("- ") || clean.startsWith("* ")) {
          clean = clean.substring(2)
        }
        return `<li class="text-[13px] text-muted-foreground/95 font-medium leading-relaxed select-text font-sans">${parseInline(clean)}</li>`
      })
      return `<ul class="list-disc pl-5 my-4.5 space-y-2 select-text font-sans">${items.join("")}</ul>`
    }
    
    // Default: Paragraph
    const paragraphText = trimmed.split("\n").join("<br />")
    return `<p class="mb-4 text-[13px] text-muted-foreground/95 font-medium leading-relaxed last:mb-0 select-text font-sans">${parseInline(paragraphText)}</p>`
  })
  
  return parsedBlocks.filter(b => b !== "").join("\n")
}

export default function FindQuestionsPage() {
  const [query, setQuery] = useState("")
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<QuestionsResult | null>(null)
  const [filterText, setFilterText] = useState("")
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null)
  const [copiedTopicIndex, setCopiedTopicIndex] = useState<number | null>(null)
  const [paaProvider, setPaaProvider] = useState<"serper" | "dataforseo">("serper")
  const [country, setCountry] = useState("us")
  const [language, setLanguage] = useState("en")
  const [model, setModel] = useState("gpt-4o")
  
  // Brand Persona & ICP states
  const [persona, setPersona] = useState("")
  const [icp, setIcp] = useState("")
  const [showPersona, setShowPersona] = useState(false)
  const [savingPersona, setSavingPersona] = useState(false)

  // GEO Post Generator States
  const [generatingPostIndex, setGeneratingPostIndex] = useState<number | null>(null)
  const [generatedPost, setGeneratedPost] = useState<string | null>(null)
  const [showPostModal, setShowPostModal] = useState(false)
  const [activePostQuestion, setActivePostQuestion] = useState("")

  // Dynamic OpenRouter & Groq models lists preloaded with standard B2B/B2C fallbacks
  interface OpenRouterModel {
    id: string
    name: string
  }
  const [openRouterModels, setOpenRouterModels] = useState<OpenRouterModel[]>([
    { id: "deepseek/deepseek-chat", name: "DeepSeek V3 (Chat)" },
    { id: "meta-llama/llama-3.3-70b-instruct", name: "Llama 3.3 70b" },
    { id: "google/gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    { id: "google/gemini-2.5-flash", name: "Gemini 2.5 Flash" }
  ])
  const [groqModels, setGroqModels] = useState<OpenRouterModel[]>([
    { id: "llama-3.3-70b-versatile", name: "Llama 3.3 70b" },
    { id: "llama-3.1-8b-instant", name: "Llama 3.1 8b" },
    { id: "mixtral-8x7b-32768", name: "Mixtral 8x7b" }
  ])
  const [loadingModels, setLoadingModels] = useState(false)

  // Save/Load last successful search from local storage for a premium UX
  useEffect(() => {
    const saved = localStorage.getItem("last-questions-result")
    if (saved) {
      try {
        setResult(JSON.parse(saved))
      } catch {
        // ignore invalid json
      }
    }
    const savedProvider = localStorage.getItem("paa-provider")
    if (savedProvider === "serper" || savedProvider === "dataforseo") {
      setPaaProvider(savedProvider)
    }
    const savedCountry = localStorage.getItem("paa-country")
    if (savedCountry) {
      setCountry(savedCountry)
    }
    const savedLanguage = localStorage.getItem("paa-language")
    if (savedLanguage) {
      setLanguage(savedLanguage)
    }
    const savedModel = localStorage.getItem("paa-model")
    if (savedModel) {
      setModel(savedModel)
    }

    // Load default Persona & ICP from Supabase settings
    async function loadSettings() {
      try {
        const { data, error } = await supabase
          .from("settings")
          .select("harvey_profile, icp")
          .eq("id", 1)
          .single()
        
        if (data && !error) {
          setPersona(data.harvey_profile || "")
          setIcp(data.icp || "")
        }
      } catch (err) {
        console.error("Failed to load brand persona from settings:", err)
      }
    }
    loadSettings()

    // Fetch dynamic models for both Groq and OpenRouter securely from backend
    async function loadDynamicModels() {
      setLoadingModels(true)
      try {
        const res = await fetch("/api/research/models")
        if (res.ok) {
          const json = await res.json()
          if (json.groq && json.groq.length > 0) {
            setGroqModels(json.groq)
          }
          if (json.openrouter && json.openrouter.length > 0) {
            setOpenRouterModels(json.openrouter)
          }
        }
      } catch (err) {
        console.error("Failed to load dynamic models:", err)
      } finally {
        setLoadingModels(false)
      }
    }
    loadDynamicModels()
  }, [])

  async function handleSavePersona() {
    setSavingPersona(true)
    try {
      const { error } = await supabase
        .from("settings")
        .update({ harvey_profile: persona, icp: icp })
        .eq("id", 1)
      
      if (error) throw error
      toast({
        title: "Settings saved",
        description: "Successfully updated brand persona and ICP in database.",
      })
    } catch (err: any) {
      toast({
        title: "Save failed",
        description: err.message || "Failed to update settings.",
        variant: "destructive",
      })
    } finally {
      setSavingPersona(false)
    }
  }

  async function handleSearch() {
    if (!query.trim()) return
    setLoading(true)
    setResult(null)

    try {
      const res = await fetch("/api/research/questions", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ phrase: query.trim(), paaProvider, country, language, model, persona, icp }),
      })

      if (!res.ok) {
        const errorData = await res.json()
        throw new Error(errorData.error || "Failed to analyze questions")
      }

      const data = await res.json()
      setResult(data)
      localStorage.setItem("last-questions-result", JSON.stringify(data))
      localStorage.setItem("paa-provider", paaProvider)
      localStorage.setItem("paa-country", country)
      localStorage.setItem("paa-language", language)
      localStorage.setItem("paa-model", model)
      
      toast({
        title: "Analysis complete",
        description: `Successfully synthesized ${data.questions.length} questions and ${data.sources.length} sources.`,
      })
    } catch (err: any) {
      toast({
        title: "Search failed",
        description: err.message || "Connection error. Make sure your local server is running.",
        variant: "destructive",
      })
    } finally {
      setLoading(false)
    }
  }

  function handleCopy(text: string, index: number, isTopic = false) {
    navigator.clipboard.writeText(text)
    if (isTopic) {
      setCopiedTopicIndex(index)
      setTimeout(() => setCopiedTopicIndex(null), 2000)
    } else {
      setCopiedIndex(index)
      setTimeout(() => setCopiedIndex(null), 2000)
    }
    toast({
      description: "Copied to clipboard!",
    })
  }

  async function handleGeneratePost(questionText: string, geoStrategy: string, index: number) {
    if (generatingPostIndex !== null) return
    setGeneratingPostIndex(index)
    try {
      const response = await fetch("/api/research/questions/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          question: questionText,
          geoStrategy: geoStrategy,
          model: model,
          persona: persona,
          icp: icp
        })
      })

      if (!response.ok) {
        throw new Error("Failed to generate post outline")
      }

      const data = await response.json()
      setGeneratedPost(data.post)
      setActivePostQuestion(questionText)

      toast({
        title: "GEO Post Outline Generated",
        description: "Your GEO-friendly post has been fully generated and is ready to copy!",
      })
    } catch (err: any) {
      toast({
        title: "Generation failed",
        description: err.message || "Could not generate post. Make sure your API keys are set.",
        variant: "destructive",
      })
    } finally {
      setGeneratingPostIndex(null)
    }
  }

  const filteredQuestions = result?.questions.filter(
    (q) => {
      if (!q) return false
      const qText = typeof q === 'string' ? q : (q.question || "")
      const intentText = typeof q === 'string' ? "Search Intent" : (q.search_intent || "")
      return (
        qText.toLowerCase().includes(filterText.toLowerCase()) ||
        intentText.toLowerCase().includes(filterText.toLowerCase())
      )
    }
  ) || []

  return (
    <div className="space-y-6 max-w-6xl mx-auto px-2 pb-12">
      {/* Header section */}
      <div className="flex flex-col gap-1.5 animate-slide-up">
        <h1 className="text-xl font-bold text-foreground flex items-center gap-2">
          <HelpCircle className="h-5 w-5 text-accent animate-pulse" />
          Find Questions Engine
        </h1>
        <p className="text-xs text-muted-foreground">
          Identify organic search queries, map user search intents, and uncover high-ranking Reddit discussions for your niche.
        </p>
      </div>

      {/* Input panel */}
      <Card className="rounded-2xl border border-border bg-card/60 backdrop-blur-md p-4 shadow-sm bg-gradient-to-br from-card to-accent/5 animate-slide-up">
        <div className="flex flex-col gap-4">
          <div className="flex flex-col gap-3">
            <div className="space-y-1">
              <h2 className="text-xs font-bold text-foreground flex items-center gap-1.5">
                <Sparkles className="h-3.5 w-3.5 text-accent" />
                Niche Query Search
              </h2>
              <p className="text-[10px] text-muted-foreground">
                Enter your target service (e.g. real estate crm development services, pet care development)
              </p>
            </div>

            <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2 w-full mt-1">
              <div className="flex-1 min-w-0">
                <Input
                  placeholder="Enter business niche or product topic..."
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && handleSearch()}
                  disabled={loading}
                  className="text-xs h-9 bg-background/80 w-full"
                />
              </div>
              <div className="flex items-center gap-2 w-full sm:w-auto shrink-0">
                <select
                  value={model}
                  onChange={(e) => setModel(e.target.value)}
                  disabled={loading}
                  className="text-[10px] bg-background/85 border border-border/55 rounded-md px-1.5 h-9 focus:outline-none focus:ring-1 focus:ring-accent text-foreground disabled:opacity-50 font-medium cursor-pointer flex-1 sm:flex-initial sm:w-[150px] min-w-[110px]"
                >
                  <optgroup label="OpenAI (Default)">
                    <option value="gpt-4o">GPT-4o (Premium)</option>
                    <option value="gpt-4o-mini">GPT-4o-mini (Fast)</option>
                  </optgroup>
                  <optgroup label="Anthropic">
                    <option value="claude-3-5-sonnet">Claude 3.5 Sonnet</option>
                    <option value="claude-3-5-haiku">Claude 3.5 Haiku</option>
                  </optgroup>
                  <optgroup label={`Groq (${loadingModels ? "Loading..." : "Dynamic"})`}>
                    {groqModels.map((m) => (
                      <option key={m.id} value={m.id}>
                        {m.name}
                      </option>
                    ))}
                  </optgroup>
                  <optgroup label={`OpenRouter (${loadingModels ? "Loading..." : "Dynamic"})`}>
                    {openRouterModels.map((m) => (
                      <option key={m.id} value={m.id}>
                        {m.name}
                      </option>
                    ))}
                  </optgroup>
                </select>
                <Button
                  onClick={handleSearch}
                  disabled={loading || !query.trim()}
                  size="sm"
                  className="h-9 px-4 gap-1.5 rounded-lg bg-accent hover:bg-accent/90 flex-1 sm:flex-initial justify-center"
                >
                  {loading ? (
                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                  ) : (
                    <Send className="h-3.5 w-3.5" />
                  )}
                  Analyze
                </Button>
              </div>
            </div>
          </div>

          <Separator className="bg-border/30" />

          <div className="flex flex-wrap items-center gap-x-6 gap-y-3">
            {/* Provider Toggle */}
            <div className="flex items-center gap-2">
              <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-wider">
                Google PAA Provider:
              </span>
              <div className="flex items-center gap-1.5 bg-background/40 border border-border/50 p-0.5 rounded-lg w-fit">
                <button
                  type="button"
                  onClick={() => setPaaProvider("serper")}
                  disabled={loading}
                  className={`px-3 py-0.5 rounded-md text-[9px] font-bold transition-all ${
                    paaProvider === "serper"
                      ? "bg-accent/15 text-accent border border-accent/10 shadow-sm"
                      : "text-muted-foreground hover:text-foreground"
                  } ${loading ? "opacity-50 cursor-not-allowed" : ""}`}
                >
                  Serper.dev (Free/Fast)
                </button>
                <button
                  type="button"
                  onClick={() => setPaaProvider("dataforseo")}
                  disabled={loading}
                  className={`px-3 py-0.5 rounded-md text-[9px] font-bold transition-all ${
                    paaProvider === "dataforseo"
                      ? "bg-accent/15 text-accent border border-accent/10 shadow-sm"
                      : "text-muted-foreground hover:text-foreground"
                  } ${loading ? "opacity-50 cursor-not-allowed" : ""}`}
                >
                  DataForSEO (Premium)
                </button>
              </div>
            </div>

            {/* Country Selector */}
            <div className="flex items-center gap-2">
              <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-wider">
                Country (gl):
              </span>
              <select
                value={country}
                onChange={(e) => setCountry(e.target.value)}
                disabled={loading}
                className="text-[10px] bg-background/80 border border-border/50 rounded-md px-1.5 h-6.5 focus:outline-none focus:ring-1 focus:ring-accent text-foreground disabled:opacity-50 max-w-[140px]"
              >
                <option value="us">United States (us)</option>
                <option value="gb">United Kingdom (gb)</option>
                <option value="ca">Canada (ca)</option>
                <option value="au">Australia (au)</option>
                <option value="in">India (in)</option>
                <option value="de">Germany (de)</option>
                <option value="fr">France (fr)</option>
                <option value="it">Italy (it)</option>
                <option value="es">Spain (es)</option>
                <option value="br">Brazil (br)</option>
                <option value="mx">Mexico (mx)</option>
                <option value="jp">Japan (jp)</option>
                <option value="cn">China (cn)</option>
                <option value="ru">Russia (ru)</option>
                <option value="za">South Africa (za)</option>
                <option value="sa">Saudi Arabia (sa)</option>
                <option value="ae">United Arab Emirates (ae)</option>
                <option value="nl">Netherlands (nl)</option>
                <option value="se">Sweden (se)</option>
                <option value="no">Norway (no)</option>
                <option value="dk">Denmark (dk)</option>
                <option value="fi">Finland (fi)</option>
                <option value="pl">Poland (pl)</option>
                <option value="ch">Switzerland (ch)</option>
                <option value="at">Austria (at)</option>
                <option value="ie">Ireland (ie)</option>
                <option value="nz">New Zealand (nz)</option>
                <option value="sg">Singapore (sg)</option>
                <option value="hk">Hong Kong (hk)</option>
                <option value="my">Malaysia (my)</option>
                <option value="id">Indonesia (id)</option>
                <option value="th">Thailand (th)</option>
                <option value="ph">Philippines (ph)</option>
                <option value="vn">Vietnam (vn)</option>
                <option value="kr">South Korea (kr)</option>
                <option value="tr">Turkey (tr)</option>
                <option value="ua">Ukraine (ua)</option>
                <option value="ar">Argentina (ar)</option>
                <option value="co">Colombia (co)</option>
                <option value="cl">Chile (cl)</option>
                <option value="pe">Peru (pe)</option>
                <option value="ve">Venezuela (ve)</option>
                <option value="pk">Pakistan (pk)</option>
                <option value="bd">Bangladesh (bd)</option>
                <option value="eg">Egypt (eg)</option>
                <option value="ng">Nigeria (ng)</option>
                <option value="ke">Kenya (ke)</option>
              </select>
            </div>

            {/* Language Selector */}
            <div className="flex items-center gap-2">
              <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-wider">
                Language (hl):
              </span>
              <select
                value={language}
                onChange={(e) => setLanguage(e.target.value)}
                disabled={loading}
                className="text-[10px] bg-background/80 border border-border/50 rounded-md px-1.5 h-6.5 focus:outline-none focus:ring-1 focus:ring-accent text-foreground disabled:opacity-50 max-w-[120px]"
              >
                <option value="en">English (en)</option>
                <option value="es">Spanish (es)</option>
                <option value="fr">French (fr)</option>
                <option value="de">German (de)</option>
                <option value="it">Italian (it)</option>
                <option value="pt">Portuguese (pt)</option>
                <option value="nl">Dutch (nl)</option>
                <option value="ja">Japanese (ja)</option>
                <option value="zh">Chinese (zh)</option>
                <option value="ru">Russian (ru)</option>
                <option value="ar">Arabic (ar)</option>
                <option value="hi">Hindi (hi)</option>
                <option value="ko">Korean (ko)</option>
                <option value="tr">Turkish (tr)</option>
                <option value="pl">Polish (pl)</option>
                <option value="sv">Swedish (sv)</option>
                <option value="no">Norwegian (no)</option>
                <option value="fi">Finnish (fi)</option>
                <option value="da">Danish (da)</option>
                <option value="el">Greek (el)</option>
                <option value="he">Hebrew (he)</option>
                <option value="id">Indonesian (id)</option>
                <option value="ms">Malay (ms)</option>
                <option value="th">Thai (th)</option>
                <option value="vi">Vietnamese (vi)</option>
                <option value="uk">Ukrainian (uk)</option>
              </select>
            </div>

            <span className="text-[9px] text-muted-foreground ml-auto hidden xl:inline">
              {paaProvider === "serper"
                ? "Uses Serper.dev PAA engine with direct Google organic PAA scraping"
                : "Uses DataForSEO Live Serp API (requires a funded, active account)"}
            </span>
          </div>
        </div>
      </Card>

      {/* Brand Persona & ICP settings (Collapsible) */}
      <Card className="rounded-2xl border border-border bg-card/60 backdrop-blur-md p-4 shadow-sm bg-gradient-to-br from-card to-accent/5 animate-slide-up">
        <button
          type="button"
          onClick={() => setShowPersona(!showPersona)}
          className="flex items-center justify-between w-full text-left focus:outline-none cursor-pointer"
        >
          <div className="space-y-1">
            <h3 className="text-xs font-bold text-foreground flex items-center gap-1.5">
              <Brain className="h-3.5 w-3.5 text-accent animate-pulse" />
              Brand Persona & ICP Configuration
            </h3>
            <p className="text-[9px] text-muted-foreground">
              Configure your brand voice and ideal customer profile (ICP) to generate highly tailored, brand-specific questions and topics.
            </p>
          </div>
          <span className="text-[10px] text-accent font-semibold px-2 py-0.5 rounded-md hover:bg-accent/10 transition-all">
            {showPersona ? "Collapse" : "Expand"}
          </span>
        </button>

        {showPersona && (
          <div className="mt-4 space-y-4 animate-fade-in">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <label className="text-[9px] font-bold text-muted-foreground uppercase tracking-wider block">
                  Brand Persona Profile
                </label>
                <textarea
                  value={persona}
                  onChange={(e) => setPersona(e.target.value)}
                  disabled={loading}
                  placeholder="Describe your brand persona, core expertise, and voice rules..."
                  rows={4}
                  className="w-full text-xs bg-background/80 border border-border/50 rounded-lg p-2.5 focus:outline-none focus:ring-1 focus:ring-accent text-foreground disabled:opacity-50 resize-y"
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-[9px] font-bold text-muted-foreground uppercase tracking-wider block">
                  Ideal Customer Profile (ICP)
                </label>
                <textarea
                  value={icp}
                  onChange={(e) => setIcp(e.target.value)}
                  disabled={loading}
                  placeholder="Describe your target buyer, industry, company size, and main pain points..."
                  rows={4}
                  className="w-full text-xs bg-background/80 border border-border/50 rounded-lg p-2.5 focus:outline-none focus:ring-1 focus:ring-accent text-foreground disabled:opacity-50 resize-y"
                />
              </div>
            </div>

            <div className="flex justify-end gap-2.5">
              <Button
                onClick={handleSavePersona}
                disabled={savingPersona || loading}
                variant="outline"
                size="sm"
                className="h-8 text-[10px] px-3 font-semibold border-border/50 bg-background/60 hover:bg-background/80 hover:text-foreground"
              >
                {savingPersona ? "Saving..." : "Save to Database"}
              </Button>
            </div>
          </div>
        )}
      </Card>

      {/* Loading state */}
      {loading && (
        <div className="flex flex-col items-center justify-center py-20 space-y-4">
          <Loader2 className="h-8 w-8 animate-spin text-accent" />
          <div className="space-y-1 text-center">
            <p className="text-xs font-semibold text-foreground">Scraping Search Pages & Forums...</p>
            <p className="text-[10px] text-muted-foreground max-w-xs animate-pulse">
              Querying {paaProvider === "serper" ? "Serper.dev PAA" : "DataForSEO PAA"}, searching Reddit threads, and synthesizing content strategy. This may take up to 30 seconds.
            </p>
          </div>
        </div>
      )}

      {/* Results view */}
      {result && !loading && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 animate-fade-in">
          
          {/* Left panel: Subreddits, Sources, Analytics */}
          <div className="col-span-1 space-y-6">
            
            {/* Overview / Metadata */}
            <Card className="rounded-2xl border border-border bg-card/60 p-4 space-y-3.5 shadow-sm">
              <span className="text-[10px] uppercase font-bold tracking-wider text-muted-foreground block">
                Analysis Insights
              </span>
              
              <div className="grid grid-cols-2 gap-3 text-xs">
                <div className="bg-background/40 p-2.5 rounded-xl border border-border/50">
                  <span className="text-[9px] text-muted-foreground block">Threads Analyzed</span>
                  <span className="text-sm font-bold text-foreground">{result.threads_analyzed} posts</span>
                </div>
                <div className="bg-background/40 p-2.5 rounded-xl border border-border/50">
                  <span className="text-[9px] text-muted-foreground block">Caching Status</span>
                  <span className="text-sm font-bold text-accent">{result.cached ? "Cached" : "Live Fetch"}</span>
                </div>
              </div>

              <div className="space-y-1.5 pt-1.5 border-t border-border/20">
                <span className="text-[9px] uppercase font-bold tracking-wider text-muted-foreground block">
                  Target Subreddits
                </span>
                <div className="flex flex-wrap gap-1.5">
                  {result.subreddits.map((sub, sIdx) => (
                    <Badge key={sIdx} variant="secondary" className="bg-orange-500/10 text-orange-500 border-orange-500/15 text-[10px] py-0.5 px-2">
                      r/{sub}
                    </Badge>
                  ))}
                </div>
              </div>
            </Card>

            {/* Sources (Reddit threads) */}
            <Card className="rounded-2xl border border-border bg-card/60 p-4 space-y-3.5 shadow-sm">
              <h3 className="text-xs uppercase font-bold tracking-wider text-muted-foreground flex items-center gap-1.5">
                <TrendingUp className="h-3.5 w-3.5 text-accent animate-pulse" />
                Reddit Forum Sources
              </h3>
              
              <div className="flex flex-col gap-2">
                {result.sources.length === 0 ? (
                  <p className="text-[10px] text-muted-foreground italic text-center py-4">No matching Reddit sources found.</p>
                ) : (
                  result.sources.map((src, idx) => (
                    <div
                      key={idx}
                      className="p-2.5 rounded-xl border border-border/60 bg-background/40 flex items-start justify-between gap-3 text-xs hover:border-accent/20 transition-all duration-200"
                    >
                      <div className="min-w-0 space-y-1">
                        <p className="font-semibold text-foreground truncate leading-snug">{src.title}</p>
                        <span className="text-[9px] py-0.5 px-1.5 bg-orange-500/10 text-orange-500 rounded font-medium">
                          r/{src.subreddit}
                        </span>
                      </div>
                      <a
                        href={src.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="p-1.5 rounded hover:bg-muted text-muted-foreground hover:text-accent transition-colors shrink-0"
                      >
                        <ExternalLink className="h-3.5 w-3.5" />
                      </a>
                    </div>
                  ))
                )}
              </div>
            </Card>
          </div>

          {/* Right panel: Questions & Bonus Topics */}
          <div className="col-span-1 lg:col-span-2 space-y-6">
            
            {/* Questions list */}
            <Card className="rounded-2xl border border-border bg-card/60 p-4 space-y-4 shadow-sm relative overflow-hidden bg-gradient-to-br from-card to-secondary/15">
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 border-b border-border/20 pb-3">
                <div className="space-y-0.5">
                  <h3 className="text-xs uppercase font-bold tracking-wider text-muted-foreground flex items-center gap-1.5">
                    <Brain className="h-3.5 w-3.5 text-accent animate-pulse" />
                    Target Search Questions ({filteredQuestions.length})
                  </h3>
                  <p className="text-[10px] text-muted-foreground">
                    Title-cased SEO search phrases mapped by consumer search intent.
                  </p>
                </div>
                
                <div className="relative max-w-xs w-full">
                  <Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground" />
                  <Input
                    placeholder="Filter questions..."
                    value={filterText}
                    onChange={(e) => setFilterText(e.target.value)}
                    className="pl-8 text-xs h-8 bg-background/50 border-border/80"
                  />
                </div>
              </div>

              <div className="space-y-2 max-h-[420px] overflow-y-auto pr-1">
                {filteredQuestions.length === 0 ? (
                  <p className="text-xs text-muted-foreground italic text-center py-12">No matching questions found.</p>
                ) : (
                  filteredQuestions.map((q, idx) => {
                    const qText = typeof q === 'string' ? q : (q.question || "Unknown Question")
                    const intentText = typeof q === 'string' ? "Search Intent" : (q.search_intent || "General Intent")
                    const geoStrategy = typeof q === 'string' ? null : q.geo_strategy
                    return (
                      <div
                        key={idx}
                        className="p-3 rounded-xl border border-border/60 bg-background/50 hover:bg-background/80 hover:border-accent/15 transition-all duration-200 flex items-start justify-between gap-4 text-xs group animate-fade-in"
                      >
                        <div className="space-y-1 flex-1 min-w-0">
                          <p className="font-bold text-foreground leading-snug">{qText}</p>
                          <div className="flex items-center gap-2">
                            <span className="text-[9px] py-0.5 px-1.5 bg-accent/10 text-accent rounded uppercase font-medium tracking-wide">
                              {intentText}
                            </span>
                          </div>
                          {geoStrategy && (
                            <p className="text-[10px] text-muted-foreground bg-accent/[0.02] border border-accent/5 rounded-lg p-2.5 mt-1.5 leading-relaxed flex items-start gap-1.5 animate-fade-in font-medium">
                              <Sparkles className="h-3 w-3 text-accent shrink-0 mt-0.5" />
                              <span>
                                <strong className="text-accent font-semibold">GEO Strategy:</strong> {geoStrategy}
                              </span>
                            </p>
                          )}
                        </div>

                        <div className="flex items-center gap-1.5 opacity-60 group-hover:opacity-100 transition-opacity shrink-0">
                          {geoStrategy && (
                            <Button
                              size="icon"
                              variant="ghost"
                              onClick={() => handleGeneratePost(qText, geoStrategy, idx)}
                              disabled={generatingPostIndex !== null}
                              className="h-7 w-7 rounded-lg text-muted-foreground hover:text-accent disabled:opacity-50"
                              title="Generate GEO-friendly Post Outline"
                            >
                              {generatingPostIndex === idx ? (
                                <Loader2 className="h-3.5 w-3.5 animate-spin text-accent" />
                              ) : (
                                <Wand2 className="h-3.5 w-3.5 text-accent/85" />
                              )}
                            </Button>
                          )}
                          <Button
                            size="icon"
                            variant="ghost"
                            onClick={() => handleCopy(qText, idx)}
                            className="h-7 w-7 rounded-lg text-muted-foreground hover:text-accent"
                            title="Copy Question"
                          >
                            {copiedIndex === idx ? (
                              <Check className="h-3.5 w-3.5 text-emerald-500" />
                            ) : (
                              <Copy className="h-3.5 w-3.5" />
                            )}
                          </Button>
                        </div>
                      </div>
                    )
                  })
                )}
              </div>
            </Card>

            {/* Bonus Topics */}
            <Card className="rounded-2xl border border-border bg-card/60 p-4 space-y-4 shadow-sm">
              <div className="border-b border-border/20 pb-3">
                <h3 className="text-xs uppercase font-bold tracking-wider text-muted-foreground flex items-center gap-1.5">
                  <BookOpen className="h-3.5 w-3.5 text-accent animate-pulse" />
                  Recommended Blog & Social Topics
                </h3>
                <p className="text-[10px] text-muted-foreground">
                  High-intent content strategy angles designed to target these client concerns.
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {result.bonus_topics.map((topic, idx) => (
                  <div
                    key={idx}
                    className="p-3 rounded-xl border border-border/60 bg-background/40 hover:bg-background/80 hover:border-accent/10 transition-all duration-200 flex items-start justify-between gap-3 text-xs group"
                  >
                    <span className="font-semibold text-foreground/90 leading-snug">{topic}</span>
                    <Button
                      size="icon"
                      variant="ghost"
                      onClick={() => handleCopy(topic, idx, true)}
                      className="h-7 w-7 rounded-lg text-muted-foreground hover:text-accent shrink-0 opacity-40 group-hover:opacity-100 transition-opacity"
                      title="Copy Topic"
                    >
                      {copiedTopicIndex === idx ? (
                        <Check className="h-3.5 w-3.5 text-emerald-500" />
                      ) : (
                        <Copy className="h-3.5 w-3.5" />
                      )}
                    </Button>
                  </div>
                ))}
              </div>
            </Card>

          </div>

        </div>
      )}

      {/* Inline Premium GEO Post Draft Panel */}
      {result && !loading && generatedPost && (
        <Card className="rounded-2xl border border-border bg-card/60 backdrop-blur-md p-6 shadow-md mt-6 bg-gradient-to-br from-card via-card to-accent/[0.01] animate-slide-up select-text border-t-4 border-t-accent">
          <CardHeader className="border-b border-border/10 pb-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 shrink-0 select-none px-0 pt-0">
            <div className="space-y-1 min-w-0">
              <span className="text-[9px] text-accent font-bold uppercase tracking-wider pl-1 flex items-center gap-1.5 animate-pulse select-none">
                <Brain className="h-3.5 w-3.5" /> Premium Content Generation Active
              </span>
              <CardTitle className="text-sm font-black text-foreground flex items-center gap-2 select-none">
                <Sparkles className="h-4 w-4 text-accent animate-pulse" />
                GEO-Optimized Post Draft
              </CardTitle>
              <CardDescription className="text-xs text-muted-foreground font-medium select-none">
                Generated for question: <strong className="text-foreground font-semibold">"{activePostQuestion}"</strong>
              </CardDescription>
            </div>
            
            <div className="flex items-center gap-2">
              <Button
                onClick={() => {
                  navigator.clipboard.writeText(generatedPost)
                  toast({ description: "Copied generated post outline to clipboard!" })
                }}
                size="sm"
                className="h-8.5 rounded-xl px-4 text-xs font-bold bg-accent hover:bg-accent/90 shadow-sm flex items-center gap-2 transition-all cursor-pointer select-none"
              >
                <Copy className="h-3.5 w-3.5" />
                Copy Post Draft
              </Button>
              <Button
                onClick={() => {
                  setGeneratedPost(null)
                  setActivePostQuestion("")
                }}
                variant="outline"
                size="sm"
                className="h-8.5 rounded-xl px-3.5 text-xs font-bold border-border/60 hover:bg-secondary/40 hover:text-foreground transition-all cursor-pointer select-none"
              >
                Clear Draft
              </Button>
            </div>
          </CardHeader>
          
          <CardContent className="p-0 pt-6 text-xs leading-relaxed text-foreground select-text selection:bg-accent/20">
            <div 
              className="select-text"
              dangerouslySetInnerHTML={{ __html: parseMarkdownToHtml(generatedPost) }}
            />
          </CardContent>
          
          <div className="border-t border-border/10 mt-6 pt-4 flex items-center justify-between text-[10px] text-muted-foreground select-none">
            <span className="font-semibold uppercase tracking-wider flex items-center gap-1">
              <Brain className="h-3 w-3 text-accent" /> Custom B2B SEO Synthesis Active
            </span>
            <span>Generated on {new Date().toLocaleDateString()}</span>
          </div>
        </Card>
      )}
    </div>
  )
}
